spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simon-spider?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

novel:
  url: https://www.rzlib.net/b/0/74/
  suffixUrl: /b/0/74/\d+\.html
